<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Formatters\Default.css" />
    <Content Include="Serialization\Format.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.12" />
  </ItemGroup>
</Project>